name: Python package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Checkout submodule
      uses: actions/checkout@v2.0.0
      with:
        token: '${{ secrets.GITHUBAPI }}'
        repository: coinpaper/utils
        path: utils
        ref: 'master'

    - name: Run pyunittests
      env:
        GITHUBAPI: ${{ secrets.GITHUBAPI }}
      run: python -m unittest

    - name: Validating YML files
      env:
        GITHUBAPI: ${{ secrets.GITHUBAPI }}
      run: python validate.py